name="atcf_hardware_bbc"
configs=["all"]
default_config="all"
base_repos=["atcf_hardware_std", "atcf_hardware_apb", "atcf_hardware_video", "atcf_hardware_io", "atcf_hardware_de1", "atcf_hardware_bbc"]
workflow="single"
stages=["clean", "build", "smoke_test", "run_bbc", "run_vnc_rfb"]
doc="""
This repository is for building, testing and running the BBC microcomputer implementation in CDL

It requires ATCF_CDL_TOOLS_PATH to point to an ATCF CDL tools grip directory configured with at least grip and CDL.
Hence $(ATCF_CDL_TOOLS_PATH)/tools/bin/cdl will be the cdl tool, and $(ATCF_CDL_TOOLS_PATH)/grip/grip will be the grip tool.

To build and run the BBC simulation, use:
  grip make run_bbc

To run the VNC RFB use:
  grip make run_vnc_rfb
"""
logging="Yes"

[env]
PATH="@ATCF_CDL_TOOLS_PATH@/tools/bin:@ATCF_CDL_TOOLS_PATH@/grip:@PATH@"
BUILD_DIR="@GRIP_ROOT_PATH@/build"
ATCF_CDL_TOOLS_PATH="@ATCF_CDL_TOOLS_PATH@"
CDL_ROOT="@ATCF_CDL_TOOLS_PATH@/tools"
VERILATOR_ROOT="@ATCF_CDL_TOOLS_PATH@/tools"
VERILATOR_SHARE="@ATCF_CDL_TOOLS_PATH@/tools/share/verilator"

[config.all]
repos=["atcf_fpga"]

[repo.atcf_hardware_std]
url="https://github.com/atthecodeface/atcf_hardware_std.git"
branch="master"
path="atcf_hardware_std"
workflow="single"

[repo.atcf_hardware_apb]
url="https://github.com/atthecodeface/atcf_hardware_apb.git"
branch="master"
path="atcf_hardware_apb"
workflow="single"
smoke_test.satisfies="smoke_test"

[repo.atcf_hardware_video]
url="https://github.com/atthecodeface/atcf_hardware_video.git"
branch="master"
path="atcf_hardware_video"
workflow="single"

[repo.atcf_hardware_io]
url="https://github.com/atthecodeface/atcf_hardware_video.git"
branch="master"
path="atcf_hardware_io"
workflow="single"

[repo.atcf_hardware_de1]
url="https://github.com/atthecodeface/atcf_hardware_video.git"
branch="master"
path="atcf_hardware_de1"
workflow="single"

[repo.atcf_hardware_bbc]
url="https://github.com/atthecodeface/atcf_hardware_bbc.git"
branch="master"
path="atcf_hardware_bbc"
workflow="single"
clean_sim.satisfies="clean"
build_sim.satisfies="build"

[repo.atcf_hardware]
url="https://github.com/atthecodeface/cdl_hardware.git"
branch="master"
path="atcf_hardware"
workflow="single"
configure={exec="autoconf && ./configure"}
build_sim={exec="make -j8"}
build_verilog={exec="make -j8 verilog"}

[repo.atcf_fpga]
url="https://github.com/atthecodeface/quartus.git"
branch="master"
path="atcf_fpga"
workflow="single"

[repo.grip]
url="https://github.com/atthecodeface/grip.git"
branch="master"
path="grip"
workflow="readonly"

